version: "3.8"
services:
  backend:
    build: ./backend
    container_name: us_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - BASE_URL=http://localhost:5000

  frontend:
    build: ./frontend
    container_name: us_frontend
    restart: unless-stopped
    ports:
      - "8080:80"
